#!/bin/sh

RRLOG="/tmp/rrlog"

if [ -n "$RRLOG" ]; then
  echo `awk '{print $1}' /proc/uptime` $REMOTE_ADDR:$REMOTE_PORT \'$HTTP_REFERER\' \'$HTTP_USER_AGENT\' >>"$RRLOG"
fi

if [ grep -q '[none]' /sys/class/leds/tp-link\:blue\:system/trigger ];then
    /usr/bin/led tp-link:blue:system timer 
else
    /usr/bin/led tp-link:blue:system none

fi

echo "Content-type: image/gif"
echo ""
cat /www/1x1.gif
